### ISSUE TITLE
App crashes on S5 with android 5

### ISSUE THREAD

**Issue by a7mag3ddon** [HiddenRambler/TagMo#17]
As title, when I click WRITE or READ tag app crashes.

**Comment by Kidel** [comment]
check my branch or @azsde 's

**Comment by a7mag3ddon** [comment]
Sorted. Thank k you :-)

**Comment by johnsmclay** [comment]
It took me over an hour to load the Android Studio and all the dependencies so I could build @azsde 's version. It worked great, but I thought others might appreciate a built APK (zipped, because Github requirement)
[TagMo_azsde_41807e7_20170315.zip](https://github.com/HiddenRambler/TagMo/files/846095/TagMo_azsde_41807e7_20170315.zip)

**Comment by DarkCodedDragon** [comment]
What are you using for phone etc . Apk doesn't work for my HTC m8 on android 4.4.4

**Comment by johnsmclay** [comment]
I grab the "Universal" APK it built. I have an axon 7 running Android 7.0.

**Comment by BSmith237** [comment]
I'm not having any luck with 2.3.2, 2.3.4 or John's build (btw, thanks for doing that).  I'm running 6.0.1 on an unrooted S6.  It'll read my Amiibo fine, seems to load keys and tags fine, crashes on "Edit SSB data", and gives me the "Transceive Error" when I try to write a tag using the "Auto" button.  Any suggestions?

**Comment by BSmith237** [comment]
I also tried the universal version of Kidel's latest branch from another issue and have used multiple cards.  Still no luck.

**Comment by Kidel** [comment]
Does it crash or you get an on screen error?

**Comment by DarkCodedDragon** [comment]
With johns build I get a java error when I go to write the tag. something java exception I think it was posted on another issue thread. Left my tags at home so cant write to one atm.

**Comment by Kidel** [comment]
does the app close or not?

**Comment by DarkCodedDragon** [comment]
If I am not writing a tag currently application will stay open and wait for tag. If tag is applied I believe it just states the java error , on other builds it says tagmo has stopped and crashes that requires relaunch of the application.  I will  be off and back home @ around 5cst so I can post full message then.

**Comment by Kidel** [comment]
if the app doesn't close but gives an on screen error (aka an handled exception), then you're doing something wrong, like using an nfc tag that is already written or not nfc215.

**Comment by DarkCodedDragon** [comment]
Thank you Kidel , I will check few more tags when I get home.  I got ten or well 9 more I will check to see if anything is loaded onto it and they should be 215 tags but never know. I know I did check before I tried to load anything on it first time and it was blank. Since then I have probably tried every build of tagmo with the same chip? Is it possible to corrupt a tag?

**Comment by Kidel** [comment]
Unlikely.

**Comment by johnsmclay** [comment]
If you are getting "Error while writing main data (stage 1) java.io.IOException: Tranceive failed"  I only get that if I try to re-write a locked tag.  If you wanna check out your tag, get NXP's Taginfo app.  After scanning  go over to the tech tab.  In memory content you should have a bunch of lines w/  " *  00 00 00 00 |****|".  If the lines start with "+r" or just "r" then it is write-protected.

**Comment by DarkCodedDragon** [comment]
I wrote to the tag that was the issue thank you
